USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'TicketAllocator')
DROP DATABASE [TicketAllocator]
GO

CREATE DATABASE [TicketAllocator]
GO

ALTER DATABASE [TicketAllocator] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TicketAllocator].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TicketAllocator] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TicketAllocator] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TicketAllocator] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TicketAllocator] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TicketAllocator] SET ARITHABORT OFF 
GO

ALTER DATABASE [TicketAllocator] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TicketAllocator] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TicketAllocator] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TicketAllocator] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TicketAllocator] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TicketAllocator] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TicketAllocator] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TicketAllocator] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TicketAllocator] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TicketAllocator] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TicketAllocator] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TicketAllocator] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TicketAllocator] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TicketAllocator] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TicketAllocator] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TicketAllocator] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TicketAllocator] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TicketAllocator] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TicketAllocator] SET  READ_WRITE 
GO

ALTER DATABASE [TicketAllocator] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TicketAllocator] SET  MULTI_USER 
GO

ALTER DATABASE [TicketAllocator] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TicketAllocator] SET DB_CHAINING OFF 
GO
